

id: <?php echo $this->item->id ?><br />
list id: <?php echo $this->item->list_id ?><br />
class: <?php echo $this->item->class ?><br />
resource id: <?php echo $this->item->resource_id ?><br />
order: <?php echo $this->item->order ?><br />
start: <?php echo $this->item->start ?><br />
end: <?php echo $this->item->end ?><br />
created: <?php echo $this->item->created ?><br />
updated: <?php echo $this->item->updated ?><br />
author: <?php echo $this->item->author ?><br />


