<h1> Kent Voyager ISBN Lookup form</h1>
<?php
	echo "old view";	
	echo $this->form;
	echo '<h2>Results</h2>';
	
	echo "<pre>";
	echo htmlspecialchars($this->kentvoyager[0], ENT_QUOTES, "UTF-8");	
	echo "</pre>";
	
	print "Title: " . $this->kv['title'] . "<br>";
	print "Author: " . $this->kv['author'] . "<br>";
	print "Edition: " . $this->kv['edition'] . "<br>";
	print "Date: " . $this->kv['published'] . "<br>";
	print "ISBN: " . $this->kv['isbn'] . "<br>";
	
?>
